controller_manager_ns: controller_manager
controller_list:
  - name: kr20/kr20_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - q1
      - q2
      - q3
      - q4
      - q5
      - q6
      - q7
      - q8
