#!/usr/bin/env python3

import rospy
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sensor_msgs.msg import JointState

from markers import *
from projectfunctions import *
import time

if __name__ == '__main__':

    # Initialize the node
    rospy.init_node("testKineControlPosition")
    print('starting motion ... ')
    # Publisher: publish to the joint_states topic
    pub = rospy.Publisher('joint_states', JointState, queue_size=10)
    # Files for the logs
    fxcurrent = open("/tmp/xcurrent.txt", "w")                
    fxdesired = open("/tmp/xdesired.txt", "w")
    fq = open("/tmp/q.txt", "w")

    # Markers for the current and desired positions
    bmarker_current  = BallMarker(color['RED'])
    bmarker_desired = BallMarker(color['GREEN'])

    # Joint names
    jnames = ['q1','q2','q3','q4','q5','q6','q7','q8']

    # Desired position
    xd = np.array([0.6, 0.6, 0.5])
    # Initial configuration
    q0 = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])

    # Resulting initial position (end effector with respect to the base link)
    T = fkine_elbry420(q0)
    x0 = T[0:3,3]

    # Red marker shows the achieved position
    bmarker_current.xyz(x0)
    # Green marker shows the desired position
    bmarker_desired.xyz(xd)

    # Instance of the JointState message
    jstate = JointState()
    # Values of the message
    jstate.header.stamp = rospy.Time.now()
    jstate.name = jnames
    # Add the head joint value (with value 0) to the joints
    jstate.position = q0

    # Frequency (in Hz) and control period 
    freq = 200
    dt = 1.0/freq
    rate = rospy.Rate(freq)

    # Initial joint configuration
    q = copy(q0)
    # Main loop
    while not rospy.is_shutdown():
        # Current time (needed for ROS)
        jstate.header.stamp = rospy.Time.now()
        # Kinematic control law for position (complete here)
        # -----------------------------
        #error = (x-xd)
        x = fkine_elbry420(q)[0:3,3]
        
        
        e = np.subtract(x.T,xd)
        k = 0.5
        edot = np.dot(-k, e)
        #edot = edot.reshape(1, -1)
	
	#Pseudoinversa de J
        J = jacobian_position(q)
        Jpseudo = np.linalg.pinv(J)
        #np.dot(np.linalg(np.dot(J.T, J)),J.T)
	
        qdot = np.dot(Jpseudo, edot)
        q = q + np.dot(dt, qdot)
        limitJoints(q)
        # -----------------------------

        
        # Log values                                                      
        fxcurrent.write(str(x[0])+' '+str(x[1]) +' '+str(x[2])+'\n')
        fxdesired.write(str(xd[0])+' '+str(xd[1])+' '+str(xd[2])+'\n')
        fq.write(str(q[0])+" "+str(q[1])+" "+str(q[2])+" "+str(q[3])+" "+
                 str(q[4])+" "+str(q[5])+" "+str(q[6])+" "+str(q[7])+"\n")
        
        # Publish the message
        jstate.position = q
        pub.publish(jstate)
        bmarker_desired.xyz(xd)
        bmarker_current.xyz(x)
        # Wait for the next iteration
        rate.sleep()

    print('ending motion ...')
    fxcurrent.close()
    fxdesired.close()
    fq.close()
    
    # Read data from log files
    xcurrent_data = np.loadtxt("/tmp/xcurrent.txt")
    xdesired_data = np.loadtxt("/tmp/xdesired.txt")
    q_data = np.loadtxt("/tmp/q.txt")

    # Generate time vector assuming constant time step
    num_samples = xcurrent_data.shape[0]
    time = np.linspace(0, num_samples / freq, num_samples)

    # Plot position as function of time
    plt.figure(figsize=(10, 8))

    plt.subplot(3, 1, 1)
    plt.plot(time, xcurrent_data[:, 0], label='Actual X')
    plt.plot(time, xdesired_data[:, 0], label='Desired X', linestyle='--')
    plt.xlabel('Time [s]')
    plt.ylabel('X Position [m]')
    plt.legend()

    plt.subplot(3, 1, 2)
    plt.plot(time, xcurrent_data[:, 1], label='Actual Y')
    plt.plot(time, xdesired_data[:, 1], label='Desired Y', linestyle='--')
    plt.xlabel('Time [s]')
    plt.ylabel('Y Position [m]')
    plt.legend()

    plt.subplot(3, 1, 3)
    plt.plot(time, xcurrent_data[:, 2], label='Actual Z')
    plt.plot(time, xdesired_data[:, 2], label='Desired Z', linestyle='--')
    plt.xlabel('Time [s]')
    plt.ylabel('Z Position [m]')
    plt.legend()

    plt.tight_layout()
    
    # Plot articular position qn
    n = 8
    plt.figure(figsize=(10, 8))
    plt.plot(time, q_data[:, n-1], label=(f"q{n} position"))
    plt.xlabel('Time [s]')
    plt.ylabel(f"q{n} position [rad]")
    plt.legend()
        
    plt.show()

    # Plot position in Cartesian space
    fig = plt.figure()
    ax = fig.gca(projection='3d')
    ax.plot(xcurrent_data[:, 0], xcurrent_data[:, 1], xcurrent_data[:, 2], label='End Effector Path')
    # Plot a single dot at the last position in xcurrent_data
    ax.scatter(xcurrent_data[-1, 0], xcurrent_data[-1, 1], xcurrent_data[-1, 2], color='red', s=100,  label='End Position')
    
    ax.scatter(xcurrent_data[0, 0], xcurrent_data[0, 1], xcurrent_data[0, 2], color='green', s=100,  label='Start Position')
    
    ax.set_xlabel('X [m]')
    ax.set_ylabel('Y [m]')
    ax.set_zlabel('Z [m]')
    ax.legend()

    plt.show()

    
